development:
  host: localhost
  database: moby_development

test:
  host: localhost
  database: moby_test

# set these environment variables on your prod server
staging:
  uri: <%= ENV["MONGOHQ_URL"] %>

production:
  uri: <%= ENV["MONGOHQ_URL"] %>
